# .goreleaser.yaml
# Documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/tool
    id: keelo
    binary: keelo

archives:
  - format: tar.gz
    # this name template makes the result look like keelo_0.1.0_linux_amd64.tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: keelo
    repository:
      owner: matansuliman
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/matansuliman/keelo"
    description: "A modular composition layer for Docker Compose."
    install: |
      bin.install "keelo"

scoops:
  - name: keelo
    repository:
      owner: matansuliman
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/matansuliman/keelo"
    description: "A modular composition layer for Docker Compose."
    license: "MIT"
