project: myapp

mixins:
  labels:
    managed-by: "keelo-cli"
    environment: "production"
  environment:
    LOG_LEVEL: "debug"
    TZ: "UTC"

modules:
  - name: api
    values:
      DB_HOST: db-myapp
      REDIS_HOST: redis-myapp
  - name: redis
  - name: postgres
