package cli

import (
	"fmt"
	"os"
	"strings"

	"keelo/internal/config"
	"keelo/internal/merger"
	"keelo/internal/modules"
	"keelo/internal/renderer"
	"keelo/pkg/types"

	"github.com/fatih/color"
	"github.com/pmezard/go-difflib/difflib"
	"github.com/spf13/cobra"
)

var diffCmd = &cobra.Command{
	Use:   "diff",
	Short: "Show differences between current and potential generated output",
	Long:  `Renders the project in-memory and compares it with the existing docker-compose.generated.yaml file.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		configPath, _ := cmd.Flags().GetString("config")

		// 1. Load Project Config
		cfg, err := config.LoadProjectConfig(configPath)
		if err != nil {
			return fmt.Errorf("loading project config: %w", err)
		}

		// 2. Load and Render Modules (In-Memory)
		loader := modules.NewLoader("modules", ".keelo/cache")
		loadedModules, err := loader.LoadProjectModules(cfg)
		if err != nil {
			return fmt.Errorf("loading modules: %w", err)
		}

		var fragments []*types.RenderedModule
		for i, modNode := range cfg.Modules {
			def, ok := loadedModules[modNode.Name]
			if !ok {
				continue
			}
			rendered, err := renderer.RenderModuleTemplate(cfg.Project, &cfg.Modules[i], def)
			if err != nil {
				return fmt.Errorf("rendering module '%s': %w", modNode.Name, err)
			}
			fragments = append(fragments, rendered)
		}

		newContent, err := merger.MergeComposeFragments(fragments, cfg.Mixins)
		if err != nil {
			return fmt.Errorf("merging compose files: %w", err)
		}

		// Add header to match the on-disk format
		header := []byte("# Code generated by keelo. DO NOT EDIT.\n# This is a generated Docker Compose file.\n\n")
		newContent = append(header, newContent...)

		// 3. Read Existing File
		oldContent, err := os.ReadFile("docker-compose.generated.yaml")
		if err != nil {
			if os.IsNotExist(err) {
				fmt.Println(color.YellowString("No existing docker-compose.generated.yaml found. Showing full new content:"))
				fmt.Println(string(newContent))
				return nil
			}
			return fmt.Errorf("reading existing file: %w", err)
		}

		// 4. Generate Diff
		diff := difflib.UnifiedDiff{
			A:        difflib.SplitLines(string(oldContent)),
			B:        difflib.SplitLines(string(newContent)),
			FromFile: "current",
			ToFile:   "new",
			Context:  3,
		}

		text, _ := difflib.GetUnifiedDiffString(diff)
		if text == "" {
			fmt.Println(color.GreenString("No changes detected."))
			return nil
		}

		// 5. Print with Colors
		lines := strings.Split(text, "\n")
		for _, line := range lines {
			if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
				color.Green(line)
			} else if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
				color.Red(line)
			} else if strings.HasPrefix(line, "@@") {
				color.Cyan(line)
			} else {
				fmt.Println(line)
			}
		}
		return nil
	},
}

func init() {
	diffCmd.Flags().StringP("config", "c", "project.yaml", "Path to project configuration file")
	rootCmd.AddCommand(diffCmd)
}
