package compose

import (
	"fmt"
	"os"
	"path/filepath"
)

// OutputWriter is responsible for writing the generated Compose file to disk.
type OutputWriter struct {
	outputFile string
}

// NewOutputWriter creates a new OutputWriter.
func NewOutputWriter(outputFile string) *OutputWriter {
	return &OutputWriter{
		outputFile: outputFile,
	}
}

// Write saves the rendered and merged YAML content to the output file.
func (w *OutputWriter) Write(content []byte) error {
	dir := filepath.Dir(w.outputFile)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory for output file '%s': %w", dir, err)
	}

	// Add a generated comment header
	header := []byte("# Code generated by keelo. DO NOT EDIT.\n# This is a generated Docker Compose file.\n\n")
	finalContent := append(header, content...)

	if err := os.WriteFile(w.outputFile, finalContent, 0644); err != nil {
		return fmt.Errorf("failed to write output file '%s': %w", w.outputFile, err)
	}

	return nil
}

// DefaultOutputFileName returns the default generated compose file name.
func DefaultOutputFileName() string {
	return "docker-compose.generated.yaml"
}
