package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestOutputWriter_Write(t *testing.T) {
	tempDir := t.TempDir()
	outPath := filepath.Join(tempDir, "docker-compose.test.yaml")

	writer := NewOutputWriter(outPath)

	testContent := []byte("services:\n  app:\n    image: nginx\n")

	if err := writer.Write(testContent); err != nil {
		t.Fatalf("Failed to write output file: %v", err)
	}

	// Verify file was created
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("Failed to read created output file: %v", err)
	}

	contentStr := string(data)

	// Verify header
	if !strings.Contains(contentStr, "# Code generated by keelo. DO NOT EDIT.") {
		t.Errorf("Missing generated comment header. Output: \n%s", contentStr)
	}

	// Verify content
	if !strings.Contains(contentStr, "services:\n  app:\n    image: nginx") {
		t.Errorf("Missing inserted content. Output: \n%s", contentStr)
	}
}

func TestDefaultOutputFileName(t *testing.T) {
	expected := "docker-compose.generated.yaml"
	if DefaultOutputFileName() != expected {
		t.Errorf("Expected default name '%s', got '%s'", expected, DefaultOutputFileName())
	}
}
